server:
  name: traveller_api
  url: localhost
  port: 9000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/travellerDB
  resources:
      chain:
        enabled: true

management:
  security:
    enabled: true

jwt:
  secretKey: traveller_api_secret_key_jwt
